### ISSUE TITLE
Non-Concrete Error when running on an ODE system

### ISSUE THREAD

**Issue by j-murphy-slingshot** [JuliaDiff/TaylorDiff.jl#35]
When running on an ODE solve the solver kicks a non-concrete error message, I've included a MWE of a Lotka-Volterra system demonstrating the behavior. I get the same error for an in-place solve

```
function lv_ode(u, p, t)
    x, y = u
    α, β, δ, γ = p

    return [α*x - β*x*y;
            δ*x*y - γ*y]
end

u0_lv = [10.0; 100.0]
p_lv = [.3; .015; .015; .7]
tspan_lv = (0.0, 100.0)

lv_prob = ODEProblem(lv_ode, u0_lv, tspan_lv, p_lv)

function taylordiff_lv(x, prob)
    _prob = remake(prob, u0=x)
    return Array(solve(_prob, Vern9(), abstol=1E-13, reltol=1E-13, save_start=false, save_everystep=false))[:, end]
end

# Checking other Derivative Methods
ad_jac = ForwardDiff.jacobian((x) -> taylordiff_lv(x, lv_prob), u0_lv)
fd_jac = FiniteDifferences.jacobian(central_fdm(5, 1), (x) -> taylordiff_lv(x, lv_prob), u0_lv)[1]

td_jac = derivative((x)->taylordiff_lv(x, lv_prob), u0_lv, [1.0; 0.0], 1)
```

> ERROR: Non-concrete element type inside of an `Array` detected.
> Arrays with non-concrete element types, such as
> `Array{Union{Float32,Float64}}`, are not supported by the
> differential equation solvers. Anyways, this is bad for
> performance so you don't want to be doing this!
> 
> If this was a mistake, promote the element types to be
> all the same. If this was intentional, for example,
> using Unitful.jl with different unit values, then use
> an array type which has fast broadcast support for
> heterogeneous values such as the ArrayPartition
> from RecursiveArrayTools.jl.

I tried using the solution suggested in the error with the line
` _prob = remake(prob, u0=ArrayPartition(x))`

and converting to an in-place solve
```
function lv_ode!(du, u, p, t)
    x, y = u
    α, β, δ, γ = p

    du[1:2] =[α*x - β*x*y;
            δ*x*y - γ*y]

    nothing
end
```

but get the the following error instead

> ERROR: MethodError: no method matching zero(::Type{Any})

**Comment by ChrisRackauckas** [comment]
@tansongchen do you have a silent conversion to Float32 somewhere? That seems pretty critical.

**Comment by ChrisRackauckas** [comment]
The array should be concretely typed, so it should `eltype(a)` shouldn't be Any from the array. If all arrays with taylor scalars are `Any` typed then performance is screwed anyways, so that should be fixed.

**Comment by ChrisRackauckas** [comment]
`eltype(TaylorScalar{Float64, 2}) == TaylorScalar{Float64, 2}` should be true. That's a property that numbers generally have.

**Comment by ChrisRackauckas** [comment]
Oh yeah because there no number type. So we need an extension for this

**Comment by ChrisRackauckas** [comment]
Why is it not `<: Number`? That doesn't seem to make sense.

**Comment by ChrisRackauckas** [comment]
```julia
td_jac = TaylorDiff.derivative((x)->taylordiff_lv(x, lv_prob), u0_lv, [1.0; 0.0], 1)

Base.real(a::TaylorScalar) = a 
DiffEqBase.UNITLESS_ABS2(x::TaylorScalar) = abs2(x)
Base.abs2(x::TaylorScalar) = abs(x^2)
Base.abs(x::TaylorScalar) = x^2 / x
DiffEqBase.value(x::TaylorScalar) = x.value[1]
Base.eltype(a::TaylorScalar) = a 
Base.iterate(a::TaylorScalar) = a
DiffEqBase.recursive_length(v::Vector{<:TaylorScalar}) = length(v)

TaylorScalar{Float64, 2}(x::Int) = TaylorScalar{Float64, 2}(float(x))

function DiffEqBase.UNITLESS_ABS2(x::AbstractArray{<:TaylorScalar})
    sum(abs2, x)
end
```

almost gets it working. But it really just points out... it's a number, it needs to extend. Otherwise it needs hundreds of definitions which are redundant of number.

**Comment by ChrisRackauckas** [comment]
With `<:Number` I'm getting close:

```julia
using OrdinaryDiffEq, TaylorDiff

function lv_ode(u, p, t)
    x, y = u
    α, β, δ, γ = p

    return [α*x - β*x*y;
            δ*x*y - γ*y]
end

u0_lv = [10.0; 100.0]
p_lv = [.3; .015; .015; .7]
tspan_lv = (0.0, 100.0)

lv_prob = ODEProblem(lv_ode, u0_lv, tspan_lv, p_lv)

function taylordiff_lv(x, prob)
    _prob = remake(prob, u0=x)
    return Array(solve(_prob, Vern9(), abstol=1E-13, reltol=1E-13, save_start=false, save_everystep=false, dt = 0.1))[:, end]
end

Base.real(a::TaylorScalar) = a 
Base.abs(x::TaylorScalar) = x^2 / x
Base.convert(::Type{TaylorScalar{T,N}}, x::Union{Int, Rational, AbstractFloat}) where {T,N} = TaylorScalar{T,N}(float(x))
TaylorScalar{T, N}(x::Union{Int, Rational}) where {T,N} = TaylorScalar{T,N}(float(x))
Base.AbstractFloat(x::TaylorScalar) = x
TaylorScalar{Float64, N}(x::BigFloat) where {N} = TaylorScalar{Float64,N}(Float64(x))
Base.isless(x::TaylorScalar, y::TaylorScalar) = x.value[1] < y.value[1]
Base.isless(x::TaylorScalar, y::Float64) = x.value[1] < y
Base.isless(x::Float64, y::TaylorScalar) = x < y.value[1]
DiffEqBase.value(x::TaylorScalar) = x.value[1]

td_jac = TaylorDiff.derivative((x)->taylordiff_lv(x, lv_prob), u0_lv, [1.0; 0.0], 1)
```

@tansongchen can we chat about this later today?

**Comment by ChrisRackauckas** [comment]
For any normal operation it should act like a number, it's just that you don't want to inherit AD rules that are defined for number. But I'm pretty sure you don't want to inherit any AD rules for that matter, and instead need to trace them to reconstruct their Taylor series approximation.

But yes we can chat 2 weeks later on this.

**Comment by orebas** [comment]
I'm a bit out of my depth, but I'll ask some questions that may help others, fully appreciating that you've tabled this for more pressing matters
1)  ForwardDiff.jl seems to allow its dual numbers to subtype Number.  Indeed, this package used to as well.  Do you have a specific example of an operation that will fail (or give a bad answer silently) if TaylorDiff does?  Is it only when TaylorDiff.jl might be used as a layer inside of another AD package?  
2) Does ForwardDiff.jl have a failure mode related to the above?  (I'm a little worried now.)

**Comment by tansongchen** [comment]
Should be fine with latest version
