### ISSUE TITLE
Add support for "fast" hyperbolic functions

### ISSUE THREAD

**Issue by mBarreau** [JuliaDiff/TaylorDiff.jl#52]
Hej,

The support of functions such as `tanh_fast` or `sigmoid_fast` is missing. I tried to add it but it seems not that easy (could it be possible to overload `tanh_fast == tanh` on a symbolic?
Would it be somehow possible to support all activation functions in NNlib?

**Comment by vpuri3** [comment]
You can add add these methods in `TaylorDiffNNlibExt` or `NNlibTaylorDiffExt` like here:

https://github.com/YichengDWu/Sophon.jl/blob/main/ext/SophonTaylorDiffExt.jl#L16-L24

**Comment by tansongchen** [comment]
Hi @vpuri3 @mBarreau , activation unctions from NNlib have been added to TaylorDiff at #67

**Comment by mBarreau** [comment]
Good job!
