### ISSUE TITLE
[TTFX] Use Packages Extensions to drop Zygote and others when not used.

### ISSUE THREAD

**Issue by lrnv** [JuliaDiff/TaylorDiff.jl#62]
TaylorDiff is depending on a lot of stuff it should not, which tanks my TTFX.

As already noted in https://github.com/JuliaDiff/TaylorDiff.jl/issues/52#issuecomment-1707801903_ , It would be very beneficial to leverage package preferences to avoid, say, having Zygote and ReverseDiff as dependencies. Formally, the composability with the AD systems is not a core functionality of the package and could be loaded ONLY when those AD systems are loaded.

**Comment by lrnv** [comment]
Taking a second look at this, It appear to me that it is onlyb the last two files `derivatives.jl` and `chainrules.jl` that are really problematic. 

For the second one, without any discussion, this code should only be loaded conditionally on chainrules ? zygote ? something. 

For the first one, the derivative interface is nice indeed, but the issue is the dependency on SlicedMap.jl, which brings along a looot of heavy dependencies, see https://github.com/mcabbott/SliceMap.jl/blob/master/Project.toml . For this reason, maybe you could reconsider the **three** instances of uses of their mapping functions and eventually replace them with something from base ? If you are worry about taking your zygote performance, then maybe an overload of these same methods should be in the condtionally loaded file. 

What do you think ?

**Comment by zhujch1** [comment]
1. The dependency SlicedMap.jl has been removed. We have introduced a more efficient implementation.

2. We are loading Zygote.jl for solving some issues in it, we will consider integrating ZygoteRules.jl as a weak dependency in the future. We can't remove Chainrules.jl, because we need to use 'frule's.

**Comment by lrnv** [comment]
For SliceMap: Thanks for removing it ! 

For Zygote : by weak-dep you mean package extension, right ?

**Comment by tansongchen** [comment]
Zygote has been added as an extension in https://github.com/JuliaDiff/TaylorDiff.jl/commit/c11dd72ce8dc2eaf1ffc2def171edd50ebe72632
