### ISSUE TITLE
How to get first n derivatives all at once efficiently?

### ISSUE THREAD

**Issue by orebas** [JuliaDiff/TaylorDiff.jl#74]
Feature request:
Based on the package design, it seems like it is probably possible to calculate the first n derivatives of a function at once (with one call).

Right now to get that out probably requires using internal details.  It would be nice to have an API to return the value and the first n derivatives at once (in a tuple or vector).  It would also be nice to have an example in the docs.

**Comment by tansongchen** [comment]
Yes, that is definitely helpful. Right now, interfaces are like

```julia
@inline function derivative(f, x, l, vN::Val{N}) where {N}
    t = make_taylor(x, l, vN)
    return extract_derivative(f(t), N)
end
```

where `make_taylor` construct the seeds, `f(t)` get the derivative and `extract_derivative` extract the N-th order. Did you mean returning `f(t)`, which is a Taylor polynomial or array of polynomials, directly?
