### ISSUE TITLE
ERROR: MethodError: no method matching make_seed(::Float64, ::Float64, ::Int64)

### ISSUE THREAD

**Issue by zahachtah** [JuliaDiff/TaylorDiff.jl#84]
Just plugging in the example from documentation gives this error from line

derivative(sin, x, 10) # scalar derivative

**Comment by tansongchen** [comment]
The examples are a bit outdated. As of v0.3.0, the order information need to be wrapped with `Val()`, like

```julia
derivative(sin, x, Val(10))
```

Thanks for pointing this out and I will be fixing that soon!

**Comment by orebas** [comment]
Hi, this just bit me.  Is there a strong reason not to have a dispatch that takes an Int and just wraps it into a Val?
