### ISSUE TITLE
Make_seed error on latest version

### ISSUE THREAD

**Issue by orebas** [JuliaDiff/TaylorDiff.jl#90]
I was getting the below error in one of my packages.  Do you happen to know a fix?  Thanks.
The source for nth_deriv_at is just

```
function nth_deriv_at(f, n::Int, t)  
	if (n == 0)
		return f(t)
	else
		return TaylorDiff.derivative(f, t, n)
	end
end
```

ERROR: LoadError: MethodError: no method matching make_seed(::Float64, ::Float64, ::Int64)
The function `make_seed` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  make_seed(::T, ::T, ::Val{P}) where {T<:Real, P}
   @ TaylorDiff ~/.julia/packages/TaylorDiff/hFSFr/src/derivative.jl:4
  make_seed(::A, ::A, ::Any) where A<:AbstractArray
   @ TaylorDiff ~/.julia/packages/TaylorDiff/hFSFr/src/derivative.jl:5

Stacktrace:
  [1] derivatives
    @ ~/.julia/packages/TaylorDiff/hFSFr/src/derivative.jl:41 [inlined]
  [2] derivative
    @ ~/.julia/packages/TaylorDiff/hFSFr/src/derivative.jl:16 [inlined]
  [3] nth_deriv_at(f::ODEParameterEstimation.AAADapprox{BaryRational.AAAapprox{Vector{Float64}}}, n::Int64, t::Float64)

**Comment by tansongchen** [comment]
there is a migration on v0.3 to use Val(n) to indicate order, for better inference. try to make your n to be a Val(n) type
